In [ ]:
import keras 
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import csv


Using TensorFlow backend.


In [8]:
train = pd.read_csv("OpenPose-Multi-Person/scaled_data.csv")

print(train)


        label     Nosex     Nosey     Neckx     Necky    R-Shox    R-Shoy  \
0    mountain  0.217391  0.019324  0.231884  0.159420  0.130435  0.159420   
1    mountain  0.185792  0.010929  0.163934  0.153005  0.071038  0.153005   
2    mountain  0.199074  0.023148  0.199074  0.175926  0.097222  0.175926   
3    mountain  0.136929  0.020747  0.141079  0.161826  0.053942  0.178423   
4    mountain  0.173184  0.011173  0.195531  0.156425  0.083799  0.156425   
..        ...       ...       ...       ...       ...       ...       ...   
129  mountain  0.157143  0.028571  0.157143  0.185714  0.061905  0.180952   
130  mountain  0.185714  0.028571  0.185714  0.185714  0.090476  0.185714   
131  mountain  0.181994  0.001936  0.181994  0.152953  0.060987  0.152953   
132  mountain  0.231884  0.004831  0.227053  0.169082  0.130435  0.169082   
133  mountain  0.189542  0.029412  0.189542  0.107843  0.078431  0.107843   

       R-Elbx    R-Elby  R-Wrx  ...    L-Ankx  L-Anky    R-Eyex    R-Eyey  

In [19]:
features = train.columns
features = list(set(list(features[1:])))
train.label = 0
X = train[features].values
Y = train.label.values

print(X)
print(Y)

[[0.20772947 0.49275362 0.02415459 ... 0.07729469 0.23188406 0.2173913 ]
 [0.15300546 0.47540984 0.00546448 ... 0.03825137 0.16393443 0.18579235]
 [0.14814815 0.49537037 0.02314815 ... 0.06944444 0.19907407 0.19907407]
 ...
 [0.15101646 0.51597289 0.00096805 ... 0.06001936 0.18199419 0.18199419]
 [0.19323671 0.49758454 0.00966184 ... 0.06763285 0.22705314 0.23188406]
 [0.15686275 0.48366013 0.00326797 ... 0.04901961 0.18954248 0.18954248]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [21]:
model = Sequential()
model.add(Dense(100,activation='relu'))
model.add(Dense(50,activation='relu'))
model.add(Dense(1))
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(X,Y,epochs=4,batch_size=100)

#epochs <- how many times the NN is trained

#batch_size <- splits the data into batches. Uses

#results = model.evaluate(x_testing,y_testing)
model.summary()

Epoch 1/4
134/134 [==============================] - 1s 5ms/step - loss: 0.0059 - accuracy: 1.0000
Epoch 2/4
134/134 [==============================] - 0s 67us/step - loss: 0.0000e+00 - accuracy: 0.9925
Epoch 3/4
134/134 [==============================] - 0s 72us/step - loss: 0.0000e+00 - accuracy: 0.9925
Epoch 4/4
134/134 [==============================] - 0s 133us/step - loss: 0.0000e+00 - accuracy: 0.9925
Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 100)               3700      
_________________________________________________________________
dense_14 (Dense)             (None, 50)                5050      
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 51        
Total params: 8,801
Trainable params: 8,801
Non-trainable params: 0
____________________________________